<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-5TCP881" failures="0" tests="4" name="Default test" time="5.301" errors="0" timestamp="2024-01-10T19:07:06 IST">
  <testcase classname="HomePage.HomePageTest" name="@BeforeTest initialize" time="5.149">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.util.logging.Logger.info(String)&amp;quot; because &amp;quot;this.log&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.logging.Logger.info(String)" because "this.log" is null
at LoginPage.LoginPageTest.validateLoginPage(LoginPageTest.java:46)
at HomePage.HomePageTest.login(HomePageTest.java:161)
at HomePage.HomePageTest.initialize(HomePageTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest initialize -->
  <testcase classname="HomePage.HomePageTest" name="validateProductList" time="0.0">
    <skipped/>
  </testcase> <!-- validateProductList -->
  <testcase classname="HomePage.HomePageTest" name="validateProductAndtheirPrice" time="0.0">
    <skipped/>
  </testcase> <!-- validateProductAndtheirPrice -->
  <testcase classname="HomePage.HomePageTest" name="validateAddtoCart" time="0.0">
    <skipped/>
  </testcase> <!-- validateAddtoCart -->
  <testcase classname="HomePage.HomePageTest" name="validateShoppingCart" time="0.0">
    <skipped/>
  </testcase> <!-- validateShoppingCart -->
  <testcase classname="HomePage.HomePageTest" name="validateFilterOption3" time="0.0">
    <ignored/>
  </testcase> <!-- validateFilterOption3 -->
  <testcase classname="HomePage.HomePageTest" name="validateFilterOption2" time="0.0">
    <ignored/>
  </testcase> <!-- validateFilterOption2 -->
</testsuite> <!-- Default test -->
